### ISSUE TITLE
View quotation cart text

### ISSUE THREAD

**Issue by bronswick** [mahafuz/product-quotation-for-woocommerce#11]
Hi 

Thanks for this, it's a really good plugin.

I was wondering if you can help, I'm trying to display the text VIEW QUOTATION CART after you click add to quote button under the button rather than on the right side?

Thanks

**Comment by mahafuz** [comment]
Hi there,
I hope you're having an amazing day.
Please use this one line of CSS on your site and you'll get what you're looking for.

```css
.woocommerce a.pqfw-view-quotation-cart {
    display: block;
}
```

A side note: If you're wondering where to put this CSS on your theme, Go to the **Appearance > Customize > Additional CSS** from the WordPress dashboard and put this line CSS on there.

#### Screenshot
https://prnt.sc/BRBrPygW_Hta
