### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Fragor69** [mahafuz/product-quotation-for-woocommerce#13]
Hello!

I want to modify some items in the Quotation Cart. For exemple, I want to hide "price" column and I want to modify 1 or 2 fields of the form (and maybe the color of the button). How can I do ? 

Thanks!

**Comment by mahafuz** [comment]
Hi Fragor69,
I hope you're having an amazing day.
Unfortunately, there is no in-build option for customizing the **Quotation Cart**.
But If you need any customized assistance, please send an email with your requirements to this email `m.mahfuz.me@gmail.com`

Thanks Best
Mahafuz

**Comment by Fragor69** [comment]
Hello, Thank you! I will send you an email right now.
